# Generated by Django 5.2 on 2025-04-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0004_contact_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='resume',
        ),
    ]
