# Generated by Django 5.2 on 2025-05-03 02:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0006_studentregistration_adhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN'),
        ),
    ]
