# Generated by Django 5.2 on 2025-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0008_studentregistration_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='work_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='work_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
